name: Test rosidl coverage
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: ros-tooling/setup-ros@master
      - uses: ros-tooling/action-ros-ci@master
        id: action-ros
        with:
          package-name: rosidl_adapter
      - name: Generate coverage report
        run: |
          pip3 install pytest-cov
          cd ${{ steps.action-ros.outputs.ros-workspace-directory-name }}
          colcon test --event-handlers console_cohesion+ --pytest-args '--cov=. --cov-report=xml' --packages-select rosidl_adapter
          sudo find . -name coverage.xml
          sudo find . -name coverage.*
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
