name: Test rosidl coverage
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: ros-tooling/setup-ros@0.0.13
        # with:
        #  required-ros-distributions: eloquent
      - uses: j-rivero/action-ros-ci@use_test_filter
        with:
          package-name: rosidl_adapter rosidl_generator_c rosidl_generator_cpp rosidl_parser rosidl_typesupport_c rosidl_typesupport_cpp
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: codecov/codecov-action@master
        # Prevent being rate limited by only reporting coverage from the Ubuntu
        # build.
        if: matrix.os == 'ubuntu-18.04'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          yml: codecov.yml
          fail_ci_if_error: false
      - uses: actions/upload-artifact@master
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log
