name: Test rosidl coverage
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: ros-tooling/setup-ros@0.0.13
      - uses: ros-tooling/action-ros-ci@master
        id: action-ros
        with:
          package-name: rosidl_adapter
      - name: Generate coverage report
        run: |
          cd ${{ steps.action-ros.outputs.ros-workspace-directory-name }}/build/rosidl_adapter
          pip3 install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
